function(enable_sanitizers target_name)
    if (NOT MYSHELL_SANITIZERS)
        return()
    endif()

    string(REPLACE "," ";" SANITIZER_LIST "${MYSHELL_SANITIZERS}")
    set(SAN_FLAGS "")

    foreach(SAN IN LISTS SANITIZER_LIST)
        string(STRIP "${SAN}" SAN)
        if (SAN STREQUAL "address")
            list(APPEND SAN_FLAGS "-fsanitize=address" "-fno-omit-frame-pointer")
        elseif (SAN STREQUAL "undefined")
            list(APPEND SAN_FLAGS "-fsanitize=undefined" "-fno-omit-frame-pointer")
        elseif (SAN STREQUAL "thread")
            list(APPEND SAN_FLAGS "-fsanitize=thread")
        elseif (SAN STREQUAL "leak")
            list(APPEND SAN_FLAGS "-fsanitize=leak")
        endif()
    endforeach()

    if (SAN_FLAGS)
        target_compile_options(${target_name} PRIVATE ${SAN_FLAGS})
        target_link_options(${target_name} PRIVATE ${SAN_FLAGS})
    endif()
endfunction()
